[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_openbooks = "4EFSQt73xMA7Mtaw8tsMd27kVyJH9KiBzEeYQhFrtT1E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
